# Projet : Analysons la qualité de l'air 💨💨

Objectif : nettoyer un fichier csv pour qu'il ne continne plus aucune erreur

## 1 . Import et analyse du jeu de données

Source : https://public.opendatasoft.com/explore/dataset/openaq/export/?disjunctive.city&disjunctive.location&disjunctive.measurements_parameter

In [20]:
import pandas as pd
import numpy as np

df = pd.read_csv('openaq.csv', on_bad_lines='skip', delimiter=";")
#vérifications du type de données par colonne
print(df.dtypes)
df.head()

Country Code      object
City              object
Location          object
Coordinates       object
Pollutant         object
Source Name       object
Unit              object
Value            float64
Last Updated      object
Country Label     object
dtype: object

,Country Code,City,Location,Coordinates,Pollutant,Source Name,Unit,Value,Last Updated,Country Label
0,DE,Manfred Lotz,"Cottbus, W.-Külz-Str.","51.75413,14.325549",PM2.5,EEA Germany,µg/m³,21.7,2016-12-21T12:00:00+01:00,Germany
1,ES,Castellón/Castelló,ES1969A,"39.8236111095,-0.24444444",NO2,EEA Spain,µg/m³,1.0,2021-07-13T08:00:00+02:00,Spain
2,ES,Valencia/València,ES1885A,"39.4802777695,-0.33638888",SO2,EEA Spain,µg/m³,5.0,2021-08-06T11:00:00+02:00,Spain
3,ES,Alicante/Alacant,ES2008A,"37.9911111095,-0.69",PM2.5,EEA Spain,µg/m³,9.0,2021-08-06T11:00:00+02:00,Spain
4,ES,Alicante/Alacant,ES1968A,"38.3511111095,-0.51388888",PM10,EEA Spain,µg/m³,1.0,2021-08-06T11:00:00+02:00,Spain

## 2 . Nettoyage du jeu de données

**Supprimer les données qui ne concernent pas la journée du 06-08-2021.**

In [21]:
#conversion en utf-8 : cela force à se débarasser des lignes dont les caractères sont illisibles
for row in df :
  row.encode('utf-8','ignore').decode("utf-8")
  
#vérifications du type de données par colonne
print(df.dtypes)
df.head()

Country Code      object
City              object
Location          object
Coordinates       object
Pollutant         object
Source Name       object
Unit              object
Value            float64
Last Updated      object
Country Label     object
dtype: object

,Country Code,City,Location,Coordinates,Pollutant,Source Name,Unit,Value,Last Updated,Country Label
0,DE,Manfred Lotz,"Cottbus, W.-Külz-Str.","51.75413,14.325549",PM2.5,EEA Germany,µg/m³,21.7,2016-12-21T12:00:00+01:00,Germany
1,ES,Castellón/Castelló,ES1969A,"39.8236111095,-0.24444444",NO2,EEA Spain,µg/m³,1.0,2021-07-13T08:00:00+02:00,Spain
2,ES,Valencia/València,ES1885A,"39.4802777695,-0.33638888",SO2,EEA Spain,µg/m³,5.0,2021-08-06T11:00:00+02:00,Spain
3,ES,Alicante/Alacant,ES2008A,"37.9911111095,-0.69",PM2.5,EEA Spain,µg/m³,9.0,2021-08-06T11:00:00+02:00,Spain
4,ES,Alicante/Alacant,ES1968A,"38.3511111095,-0.51388888",PM10,EEA Spain,µg/m³,1.0,2021-08-06T11:00:00+02:00,Spain

In [22]:
df = df.loc[df["Last Updated"].str.contains("2021-08-06")]
df

,Country Code,City,Location,Coordinates,Pollutant,Source Name,Unit,Value,Last Updated,Country Label
2,ES,Valencia/València,ES1885A,"39.4802777695,-0.33638888",SO2,EEA Spain,µg/m³,5.000,2021-08-06T11:00:00+02:00,Spain
3,ES,Alicante/Alacant,ES2008A,"37.9911111095,-0.69",PM2.5,EEA Spain,µg/m³,9.000,2021-08-06T11:00:00+02:00,Spain
4,ES,Alicante/Alacant,ES1968A,"38.3511111095,-0.51388888",PM10,EEA Spain,µg/m³,1.000,2021-08-06T11:00:00+02:00,Spain
5,ES,Valencia/València,ES1911A,"39.7052777695,-0.33666666",CO,EEA Spain,µg/m³,100.000,2021-08-06T11:00:00+02:00,Spain
6,ES,Valencia/València,ES1185A,"39.6672222195,-0.23472222",PM10,EEA Spain,µg/m³,13.000,2021-08-06T11:00:00+02:00,Spain
...,...,...,...,...,...,...,...,...,...,...
40408,TH,Bangkok,"Din Dang, Bangkok","13.7619223,100.558606",PM10,Air4Thai,µg/m³,42.000,2021-08-06T14:00:00+02:00,Thailand
40409,TH,Samut Prakan,"City Hall, Samut Prakan","13.599149,100.597345",SO2,Air4Thai,ppm,0.000,2021-08-06T13:00:00+02:00,Thailand
40410,TH,Samut Prakan,"City Hall, Samut Prakan","13.599149,100.597345",NO2,Air4Thai,ppm,0.006,2021-08-06T13:00:00+02:00,Thailand
40411,TH,Chachoengsao,Municipality Office Tungsadao,"13.588554,101.286359",PM10,Air4Thai,µg/m³,37.000,2021-08-06T13:00:00+02:00,Thailand
40412,TH,Chachoengsao,Municipality Office Tungsadao,"13.588554,101.286359",O3,Air4Thai,ppm,0.016,2021-08-06T13:00:00+02:00,Thailand

**Vérification qu'il n'y a pas de valeur de mesure manquantes**

In [23]:
# affichage des valeurs manquantes
print("\nAffichage des valeurs nulles:")
display(df.loc[df['Value'].isnull()])
display(df.loc[df['Pollutant'].isnull()])
display(df.loc[df['City'].isnull()])

Affichage des valeurs nulles:

Empty DataFrame
Columns: [Country Code, City, Location, Coordinates, Pollutant, Source Name, Unit, Value, Last Updated, Country Label]
Index: []

Empty DataFrame
Columns: [Country Code, City, Location, Coordinates, Pollutant, Source Name, Unit, Value, Last Updated, Country Label]
Index: []

,Country Code,City,Location,Coordinates,Pollutant,Source Name,Unit,Value,Last Updated,Country Label
1514,CA,NaN,Toronto Downtown,"43.64543,-79.38908",PM2.5,AirNow,µg/m³,8.000,2021-08-06T13:00:00+02:00,Canada
1516,CA,NaN,Hochelaga,"45.539928,-73.540388",PM2.5,AirNow,µg/m³,29.400,2021-08-06T13:00:00+02:00,Canada
1520,CA,NaN,Cranbrook Muriel Bax,"49.507103,-115.753682",NO2,AirNow,ppm,0.003,2021-08-06T13:00:00+02:00,Canada
2752,ID,NaN,Jakarta Central,"-6.182536,106.834235",PM2.5,AirNow,µg/m³,27.000,2021-08-06T13:00:00+02:00,Indonesia
3068,PK,NaN,Karachi,"24.8415,67.0091",PM2.5,AirNow,µg/m³,31.000,2021-08-06T13:00:00+02:00,Pakistan
...,...,...,...,...,...,...,...,...,...,...
38501,CA,NaN,Aéroport de Montréal,"45.468297,-73.741185",O3,AirNow,ppm,0.033,2021-08-06T13:00:00+02:00,Canada
38502,CA,NaN,Aéroport de Montréal,"45.468297,-73.741185",NO2,AirNow,ppm,0.003,2021-08-06T13:00:00+02:00,Canada
38503,CA,NaN,Flat Valley,"54.294639,-109.209214",O3,AirNow,ppm,0.020,2021-08-06T13:00:00+02:00,Canada
39070,CA,NaN,St-Dominique,"45.512189,-73.566872",PM2.5,AirNow,µg/m³,25.600,2021-08-06T13:00:00+02:00,Canada
40039,TX,NaN,Ashgabat,"37.9415,58.3879",PM2.5,AirNow,µg/m³,12.000,2021-08-06T13:00:00+02:00,NaN

**Vérification des valeurs négatives**

In [24]:
# suppression des valeurs négatives et nulle
toDrop = df.loc[df['Value']<=0]
df = df.drop(toDrop.index)

**Pour chaque polluant, vérifier qu'on n'a qu'une seule mesure utilisée. Autrement dit, supprimer les données qui correspondent à la mesure minoritaire ou moins cohérente.**

In [25]:
# Création d'un dataframe qui ne contient que la valeur max pour chaque ville et chaque polluant
# on pourrait aussi conserver la mesure mediane avec la fonction .med()
PollutantCount = df.groupby(['Pollutant','City'])['Value'].max()

#jointure intérieure des deux dataframe : autrement dit, suppression des données correspondant à la mesure minoritaire sauf s'il est est strictement égale au max
df = pd.merge(df, PollutantCount, on=['Pollutant', 'City', 'Value'], how='inner')

# Suppression des doublons basés sur la combinaison de colonnes 'Pollutant', 'City' et 'Value'
df.drop_duplicates(subset=['Pollutant', 'City', 'Value'], inplace=True)

df

,Country Code,City,Location,Coordinates,Pollutant,Source Name,Unit,Value,Last Updated,Country Label
0,ES,Alicante/Alacant,ES2008A,"37.9911111095,-0.69",PM2.5,EEA Spain,µg/m³,9.000,2021-08-06T11:00:00+02:00,Spain
1,ES,Alicante/Alacant,ES1849A,"38.2591666595,-0.7175",CO,EEA Spain,µg/m³,100.000,2021-08-06T11:00:00+02:00,Spain
7,ES,Almería,ES1835A,"36.9499999995,-1.96148",CO,EEA Spain,µg/m³,417.000,2021-08-06T09:00:00+02:00,Spain
8,ES,Huelva,ES0787A,"37.1903299995,-6.90453",SO2,EEA Spain,µg/m³,41.000,2021-08-06T08:00:00+02:00,Spain
9,ES,Bizkaia,ES1491A,"43.4061111095,-2.70388888",O3,EEA Spain,µg/m³,54.000,2021-08-06T04:00:00+02:00,Spain
...,...,...,...,...,...,...,...,...,...,...
8303,TH,Chiang Rai,Maesai Health Office,"20.427325,99.883842",O3,Air4Thai,ppm,0.023,2021-08-06T14:00:00+02:00,Thailand
8304,TH,Nakhon Ratchasima,Municipal Waste Water Pumping Station,"14.979726,102.098301",O3,Air4Thai,ppm,0.028,2021-08-06T14:00:00+02:00,Thailand
8305,TH,Nakhon Sawan,Nakhonsawan Irrigation Project,"15.686254,100.110542",O3,Air4Thai,ppm,0.021,2021-08-06T14:00:00+02:00,Thailand
8306,TH,Chachoengsao,Municipality Office Tungsadao,"13.588554,101.286359",PM10,Air4Thai,µg/m³,37.000,2021-08-06T13:00:00+02:00,Thailand
8307,TH,Chachoengsao,Municipality Office Tungsadao,"13.588554,101.286359",O3,Air4Thai,ppm,0.016,2021-08-06T13:00:00+02:00,Thailand

**Regarder s'il y a des valeurs aberrantes**

Détermination des quartiles : Q1 et Q3  
Quartile :Chacune des trois valeurs qui divisent les éléments d'une distribution statistique en quatre parties d'effectif égal.

In [26]:
#créations des quartiles
Q1 = round(df.groupby(['Pollutant'])['Value'].quantile(0.25),2)
Q2 = round(df.groupby(['Pollutant'])['Value'].std(),2)
Q3 = round(df.groupby(['Pollutant'])['Value'].quantile(0.75),2)

dfStats = pd.DataFrame({'Q1 value': Q1, 'Q2 value': Q2, 'Q3 value': Q3})
dfStats

           Q1 value  Q2 value  Q3 value
Pollutant
BC             0.11      0.99      0.37
CO           170.00    534.30    700.00
NO2            3.18     14.70     21.00
O3             0.03     58.13     86.00
PM10          10.61     33.01     37.00
PM2.5          5.78     37.39     19.38
SO2            1.61     15.50      8.00

In [27]:
#visualisation
dfInfQ1 = df.loc[df['Value'] < df['Pollutant'].map(Q1)].sort_values('Value')
dfSupQ3 = df.loc[df['Value'] > df['Pollutant'].map(Q3)].sort_values('Value', ascending = False)
display(dfInfQ1)
display(dfSupQ3)

,Country Code,City,Location,Coordinates,Pollutant,Source Name,Unit,Value,Last Updated,Country Label
3758,ZA,West Rand,Mogale City,"-26.170333,27.806556",SO2,South Africa,ppm,0.000008,2021-08-06T14:00:00+02:00,South Africa
7045,AU,Geelong,Geelong South,"-38.17356,144.3703",SO2,Australia - Victoria,ppm,0.000020,2021-08-06T13:00:00+02:00,Australia
5144,ZA,Mangaung Metro,Pelonomi,"-29.138507,26.241952",SO2,South Africa,ppm,0.000234,2021-08-06T14:00:00+02:00,South Africa
7954,AU,Melbourne,Alphington,"-37.7784081,145.0306",SO2,Australia - Victoria,ppm,0.000290,2021-08-06T13:00:00+02:00,Australia
4308,ZA,Garden Route,George,"-33.981195,22.473122",SO2,South Africa,ppm,0.000329,2021-08-06T14:00:00+02:00,South Africa
...,...,...,...,...,...,...,...,...,...,...
1858,LT,Vilnius,LT00004,"54.6733329995,25.248903",CO,EEA Lithuania,µg/m³,162.988000,2021-08-06T04:00:00+02:00,Lithuania
4135,EE,Tartumaa,EE0021A,"58.3705750026,26.7347611707",CO,EEA Estonia,µg/m³,163.339000,2021-08-06T14:00:00+02:00,Estonia
5036,BE,Vlaams-Brabant,BETR020,"50.941387115,4.43672076353",CO,EEA Belgium,µg/m³,165.000000,2021-08-06T03:00:00+02:00,Belgium
7233,PL,Kalisz,Kalisz-Wyszynskiego,"51.748103,18.04931",CO,GIOS,µg/m³,166.800000,2021-08-06T14:00:00+02:00,Poland
2371,EE,Ida-Virumaa,EE0022A,"59.3761713409,28.179162316",CO,EEA Estonia,µg/m³,169.140000,2021-08-06T14:00:00+02:00,Estonia

,Country Code,City,Location,Coordinates,Pollutant,Source Name,Unit,Value,Last Updated,Country Label
3811,MK,Aerodrom Municipality,MK0031A,"41.9783299995,21.47",CO,EEA Macedonia,µg/m³,10045.62320,2021-08-06T02:00:00+02:00,"Macedonia, The former Yugoslav Rep. of"
6097,CL,Talcahuano,Nueva Libertad,"-36.735998,-73.118693",CO,Chile - SINCA,µg/m³,2837.96000,2021-08-06T14:00:00+02:00,Chile
2026,CL,Cerro Navia,Cerro Navia,"-33.4330896101,-70.7321478687",CO,Chile - SINCA,µg/m³,2770.42000,2021-08-06T14:00:00+02:00,Chile
7452,CL,Santiago,Parque O'Higgins,"-33.464142,-70.660797",CO,Chile - SINCA,µg/m³,2530.01000,2021-08-06T14:00:00+02:00,Chile
6177,CN,乌兰察布市,集宁新区,"40.9923,113.1306",CO,ChinaAQIData,µg/m³,2400.00000,2021-08-06T13:00:00+02:00,China
...,...,...,...,...,...,...,...,...,...,...
833,PL,Warszawa,Warszawa-Komunikacyjna,"52.219298,21.004724",BC,GIOS,µg/m³,0.48200,2021-08-06T14:00:00+02:00,Poland
1532,PL,Słupsk,AM11 Słupsk Kniaziewicza,"54.463611,17.046722",BC,GIOS,µg/m³,0.46980,2021-08-06T14:00:00+02:00,Poland
3746,PL,Rzeszów,Rzeszów-Piłsudskiego,"50.040675,22.004656",BC,GIOS,µg/m³,0.41577,2021-08-06T14:00:00+02:00,Poland
3750,PL,Kielce,"Kielce, ul. Targowa","50.878998,20.633692",BC,GIOS,µg/m³,0.40000,2021-08-06T14:00:00+02:00,Poland
2217,PL,Złoty Potok,"Złoty Potok, Leśniczówka","50.710889,19.458797",BC,GIOS,µg/m³,0.38297,2021-08-06T14:00:00+02:00,Poland

In [28]:
#création d'un dataframe Outliers
outliers = pd.concat([dfInfQ1, dfSupQ3]).sort_values('Value')
outliers

,Country Code,City,Location,Coordinates,Pollutant,Source Name,Unit,Value,Last Updated,Country Label
3758,ZA,West Rand,Mogale City,"-26.170333,27.806556",SO2,South Africa,ppm,0.000008,2021-08-06T14:00:00+02:00,South Africa
7045,AU,Geelong,Geelong South,"-38.17356,144.3703",SO2,Australia - Victoria,ppm,0.000020,2021-08-06T13:00:00+02:00,Australia
5144,ZA,Mangaung Metro,Pelonomi,"-29.138507,26.241952",SO2,South Africa,ppm,0.000234,2021-08-06T14:00:00+02:00,South Africa
7954,AU,Melbourne,Alphington,"-37.7784081,145.0306",SO2,Australia - Victoria,ppm,0.000290,2021-08-06T13:00:00+02:00,Australia
4308,ZA,Garden Route,George,"-33.981195,22.473122",SO2,South Africa,ppm,0.000329,2021-08-06T14:00:00+02:00,South Africa
...,...,...,...,...,...,...,...,...,...,...
6177,CN,乌兰察布市,集宁新区,"40.9923,113.1306",CO,ChinaAQIData,µg/m³,2400.000000,2021-08-06T13:00:00+02:00,China
7452,CL,Santiago,Parque O'Higgins,"-33.464142,-70.660797",CO,Chile - SINCA,µg/m³,2530.010000,2021-08-06T14:00:00+02:00,Chile
2026,CL,Cerro Navia,Cerro Navia,"-33.4330896101,-70.7321478687",CO,Chile - SINCA,µg/m³,2770.420000,2021-08-06T14:00:00+02:00,Chile
6097,CL,Talcahuano,Nueva Libertad,"-36.735998,-73.118693",CO,Chile - SINCA,µg/m³,2837.960000,2021-08-06T14:00:00+02:00,Chile
3811,MK,Aerodrom Municipality,MK0031A,"41.9783299995,21.47",CO,EEA Macedonia,µg/m³,10045.623200,2021-08-06T02:00:00+02:00,"Macedonia, The former Yugoslav Rep. of"

In [29]:
#suppression des valeurs < Q1 et > Q3

#df = df.drop(dfInfQ1.index)
#df = df.drop(dfSupQ3.index)

In [30]:
#analyse du df final
ValuesPerCountry= df.value_counts(['Country Label'])
print(ValuesPerCountry)

Country Label
China             2209
United States     1457
Poland             644
United Kingdom     401
France             387
                  ...
Côte d'Ivoire        1
Chad                 1
Bangladesh           1
Bahrain              1
Viet Nam             1
Length: 64, dtype: int64

## 3. Exporter sous format CSV

In [31]:
#export des 2 df sous format csv. Index = false évite de créer une colonne index pour les équipes compta qui y comprennent rien 
df.to_csv('air_quality_v2.csv', index=False)
outliers.to_csv('outlier.csv', index=False)
ValuesPerCountry.to_csv('countries.csv')